### ISSUE TITLE
Release prebuilt binary for M1 Mac

### ISSUE THREAD

**Issue by eagletmt** [itamae-kitchen/mitamae#103]
Currently we have only darwin-i386 and darwin-x86_64 for macOS. It would be great if we had darwin-aarch64 variant.
Maybe we need recent https://github.com/tpoechtrager/osxcross and macOS SDK?

**Comment by eagletmt** [comment]
note: I've confirmed that mitamae built with `rake compile` in M1 Mac works fine for me.

**Comment by k0kubun** [comment]
Agreed. 

We use a different Dockerfile for each target here https://github.com/itamae-kitchen/mitamae/tree/master/dockcross. We're currently using hone/mruby-cli for darwin builds, but it's essentially just using https://github.com/tpoechtrager/osxcross and it shouldn't be too difficult because it already seems to support darwin-arm64.

**Comment by eagletmt** [comment]
Current status: I've successfully cross-compiled mitamae in my machine (WSL2). It uses macOS SDK created from Xcode_12.4.xip.

I've also managed to build a darwin arm64 binary in GitHub Actions, but the binary cannot be used in my M1 Mac. It causes OSStatus -67071 error, which looks errSecCSInvalidObjectRef.
https://github.com/eagletmt/mitamae/actions/runs/534756960
I need to find the difference between my WSL2 machine and GitHub Actions environment...

**Comment by eagletmt** [comment]
> the binary cannot be used in my M1 Mac. It causes OSStatus -67071 error, which looks errSecCSInvalidObjectRef.

It was my fault. Removing `com.apple.quarantine` flag solved this problem 😅 
I'm preparing PR.
