### ISSUE TITLE
new resource proposal: include_plugins

### ISSUE THREAD

**Issue by takumin** [itamae-kitchen/mitamae#81]
# Motivation

Although mitamae can be extended by plugins, plugin dependencies can not be described in recipes.

For example, in order for the user to use the snippet posted to gist, the user must either resolve the dependency himself or define the dependency in the Git repository.

My suggestion is to add a new resource, as shown below, and hope that mitamae resolves plug-in dependencies.

[Twitter Reply 1 (Japanese)](https://twitter.com/k0kubun/status/1115983283060215810)
[Twitter Reply 2 (Japanese)](https://twitter.com/k0kubun/status/1115995155759165441)
[Twitter Reply 3 (Japanese)](https://twitter.com/k0kubun/status/1116004680868360193)

# Specification

- Code syntax
- Environment variable

## Code syntax

```ruby
include_plugins [String, Array, Hash]
```

## Environment variable

When mitamae references an include_plugins resource, it checks the MITAMAE_PATH environment variable.

When undefined, the "${HOME}/.mitamae" directory is set.

When defined, the defined directory is set.

This is very compatible with the ghq command. :muscle:

# Example

- One depndency
- Many dependency
- Tar/Zip archive dependency

## One dependency

This is an example of resolving one dependency and acquiring the master branch from the Git repository.

```ruby
include_plugins 'github.com/takumin/mitamae-plugin-resource-mount'

mount '/tmp' do
  device 'tmpfs'
  type 'tmpfs'
  options [
    'defaults',
    'size=50%',
  ]
end
```

When the MITAMAE_PATH environment variable is set to "/home/takumin/.mitamae"

```
/home/takumin/.mitamae/src/github.com/takumin/mitamae-plugin-resource-mount/
+-- LICENSE
+-- README.md
+-- mrblib
    +-- resource
    |   +-- mount.rb
    +-- resource_executor
        +-- mount.rb
```

## Many dependency

This is an example of resolving multiple dependencies and acquiring master branch from Git repository respectively.

```ruby
include_plugins [
  'github.com/takumin/mitamae-plugin-resource-apt_keyring',
  'github.com/takumin/mitamae-plugin-resource-apt_repository',
]

apt_keyring 'Ubuntu-ja Archive Automatic Signing Key <archive@ubuntulinux.jp>' do
  finger '3B593C7BE6DB6A89FB7CBFFD058A05E90C4ECFEC'
  uri 'https://www.ubuntulinux.jp/ubuntu-ja-archive-keyring.gpg'
end

apt_keyring 'Launchpad PPA for Ubuntu Japanese Team' do
  finger '59676CBCF5DFD8C1CEFE375B68B5F60DCDC1D865'
  uri 'https://www.ubuntulinux.jp/ubuntu-jp-ppa-keyring.gpg'
end

apt_repository 'Ubuntu Japanese Team Repository' do
  path '/etc/apt/sources.list.d/ubuntu-ja.list'
  entry [
    {
      :default_uri => 'http://archive.ubuntulinux.jp/ubuntu',
      :mirror_uri  => "#{ENV['APT_REPO_URL_JA'] || node['apt-repo-url-ja']}",
      :suite       => '###platform_codename###',
      :source      => true,
      :components  => [
        'main',
      ],
    },
    {
      :default_uri => 'http://archive.ubuntulinux.jp/ubuntu-ja-non-free',
      :mirror_uri  => "#{ENV['APT_REPO_URL_JA_NON_FREE'] || node['apt-repo-url-ja-non-free']}",
      :suite       => '###platform_codename###',
      :source      => true,
      :components  => [
        'multiverse',
      ],
    },
  ]
end
```

When the MITAMAE_PATH environment variable is set to "/home/takumin/.mitamae"

```
/home/takumin/.mitamae/src/github.com/takumin/
+-- mitamae-plugin-resource-apt_keyring
|   +-- LICENSE
|   +-- README.md
|   +-- mrblib
|       +-- resource
|       |   +-- apt_keyring.rb
|       +-- resource_executor
|           +-- apt_keyring.rb
+-- mitamae-plugin-resource-apt_repository
    +-- LICENSE
    +-- README.md
    +-- mrblib
        +-- resource
        |   +-- apt_repository.rb
        +-- resource_executor
        |   +-- apt_repository.rb
        +-- template
            +-- apt.list.erb
```

## Tar/Zip archive dependency

This is a slightly special case, but it is useful, for example, if you want to use a plug-in that has downloaded archive files from "intranet" etc.

```ruby
include_plugins {
  'great_plugin' => {
    :uri =>     'https://example.com/great_plugin_v0.0.1alpha.zip',
    :root =>    '/great_plugin',
    :version => '0.0.1alpha',
  }
}

great_plugin 'awesome' do
  great_argument 'oops...'
end
```

The structure in the archive file is as follows:

```
/
+-- great_plugin
    +-- LICENSE
    +-- README.md
    +-- mrblib
        +-- resource
        |   +-- great_plugin.rb
        +-- resource_executor
            +-- great_plugin.rb
```

The handling of archive files is a little special, so it will be placed under "${MITAMAE_PATH}/pkg".

```
/home/takumin/.mitamae/pkg/mitamae/great_plugin/0.0.1alpha/
+-- LICENSE
+-- README.md
+-- mrblib
    +-- resource
    |   +-- great_plugin.rb
    +-- resource_executor
        +-- great_plugin.rb
```

**Comment by k0kubun** [comment]
My general policies:

* Itamae (not talking about mitamae) is designed for simplicity.
  * The plugin installation is delegated to Ruby's own ecosystem, not building it by itself like Berkshelf.
  * On the other hand, Ruby is really open and we can easily define original DSL on our own. For example, I see authors often define `include_cookbook` and `include_role` by theirselves and use them.
* As I personally like the Itamae's interface design, mitamae _tries to_ be compatible with Itamae and follow the philosophy.
  * It's really unlikely that I accept built-in support for DSL which does not exist in DSL. I rather want to make it easy to use it on user's own.
     * i.e. `include_plugins` method is not going to be defined in mitamae, while we try to support the experience itself in some ways.
  * **mitamae should use mruby's official mrbgem build system to install plugins**.
     * Another maintainer is doing it https://github.com/eagletmt/mitamae-secrets. It's already possible that you create a mitamae plugin supporting the feature in the same way.
     * Note that [the current plugin system](https://github.com/itamae-kitchen/mitamae/blob/master/PLUGINS.md) completely violates the policy, and it claims to be "experimental" from the beginning.
         * i.e. Do not expect that this kind of thing is _directly_ supported by mitamae anymore.

<hr>

That said, there're several options to achieve the described experience:

1. Build your own `include_plugins` plugin which is built like https://github.com/eagletmt/mitamae-secrets.
2. Consider proposing something to mruby for improving the mruby's build / packaging system. If it implements a really good counterpart of rubygems/bundler for mruby, I may try to implement a new plugin system whose interface is compatible with Itamae (i.e. hooked from `include_recipe`).
3. Propose the same feature to Itamae first. Once it's merged and released, I would be happy to have built-in support of the same feature in mitamae for compatibility.
4. Implement the feature as mitamae resource plugin and bootstrap `include_plugins` DSL by that. At least the current plugin system is not going to be deprecated soon because I'm using that on production :p 

<hr>

In none of the options above, mitamae side has nothing to do. So closing this issue in mitamae. Depending the option you chose, please open another issue in Itamae or mruby, or create a plugin repository.

Don't take me wrong. The feature itself looks very nice. I just believe mitamae repository is not a place to implement that directly. Thank you for discussing the plugin system.

**Comment by takumin** [comment]
Thank you for your reply.
And I apologize for not having enough my idea.
I think the options you have presented are a very good idea.
After thinking about the functions you want to change again, I would like to post them to the appropriate place.

Finally, thank you very much for giving me a polite explanation and an option for improvement.
I will continue to study in order to become an excellent software engineer like you.
