### ISSUE TITLE
Content should allow for specifying a template without a source?

### ISSUE THREAD

**Issue by moritzheiber** [itamae-kitchen/mitamae#82]
So, I might have misunderstood how the `template` resource is supposed to work, but from my early Chef days I remember that you could either specify a `source` (i.e. a file) for a `template` resource or just pass its content directly to the resource via the `content` attribute.

When I try to do with the current mitamae implementation the `template` resource fails because it's looking for a file to render (and cannot find it).

Is this intended behavior? Do I need to add an "empty" file as a template somewhere just for it be rendered correctly?

**Comment by k0kubun** [comment]
> Is this intended behavior? Do I need to add an "empty" file as a template somewhere just for it be rendered correctly?

At this moment, yes. There are 2 reasons:

1. Itamae is reference implementation for mitamae, not Chef. And that's how Itamae's `template` resource works.
2. You can use `file` resource with `content` instead of `template` resource. I can't think of any reason for making `template` available for creating an empty file.

If you really need it, please tell us what problem you want to solve by that feature, and why it's hard with `file` with `content` resource.

**Comment by k0kubun** [comment]
Ah well, if you want to write an erb template in content attribute and render it, that would make a total sense. Is that what you want, not just creating a file with non-erb content?

**Comment by moritzheiber** [comment]
@k0kubun Yup, that's exactly what I am after. I specifically chose to use the `template` resource because it accepts a `variables` attribute, which I need in order to render `content`.

**Comment by moritzheiber** [comment]
Example code:

```ruby
template '/tmp/test_file' do
  content <<CONTENT
<% @things.each do |thing| %>
This is some <%= thing %>
<% end %>
CONTENT
  variables(
    things: ['foo', 'bar']
  )
end
```

**Comment by k0kubun** [comment]
I added the feature that in v1.7.6. Please try it once it's released [here](https://travis-ci.org/itamae-kitchen/mitamae/builds/556345671).

**Comment by moritzheiber** [comment]
Works as intended, thank you!
